### PR TITLE
Added Missing Reference to Microsoft.Azure.Devices.Client.PCL

### PR DESCRIPTION
**Pull request by kunalbabre**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kunalbabre__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by iluican** [comment]
Hello,

Thank you for your contribution. However, this change is not needed. If you open the iothub_csharp_deviceclient.sln solution, you will notice that the UWPSample project references the Microsoft.Azure.Devices.Client.WinRT project directly, hence it doesn't go through Nuget. Nuget is only used to get some other dependencies.

Please let me know if you disagree with me, otherwise feel free to close this issue.

Thank you,
Ilie.

**Comment by kunalbabre** [comment]
Hi llie,

Thank you for reviewing this, I checked out this project locally and found project had issue finding reference hence the fix.

If it works fine for you happy to close.

Thanks,
Kunal

**Comment by kunalbabre** [comment]
Ignore my last comment, I see what you mean

**Pull request closed without merging**
