### PR TITLE
Azure IoTHub UWP SDK

### PR DESCRIPTION
**Pull request by RVinoth**
Azure IoTHub UWP SDK facilitates the service endpoint to send and receive cloud messages to the device end points. This SDK can be used for developing universal windows platform (UWP) in c# for windows 10 OS , developed by e-con systems and contributed to Azure IoT. This library uses AMQPNetlite to communicate with the Azure IoT hub. A sample application is provided to know the usage of the APIs.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@RVinoth__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by pierreca** [comment]
Hi @RVinoth, looks like the changelog is huge because you're including the whole source code of AmqpNetLite. Let's just reference the nuget package so that we can take an better look at the changes in the SDK itself only :) thanks!

**Comment by RVinoth** [comment]
Okay. I will remove the AQMPNetLite and commit it again. Thanks.

**Comment by RVinoth** [comment]
I have removed the AMQPNetLite, changed the readme file according to that and committed it again.

**Comment by pierreca** [comment]
Thanks! much easier to review :) 
It looks like you "recreated" an SDK all in one file (plus helper files) instead of inserting additional code in the existing SDK, I'm curious to hear why you preferred that route instead of inserting/modifying our existing codebase.

I'm asking because imho it would be much more desirable to maximize code reuse across all .NET flavors, and abstract as much as possible the transport library. We've had AMQPNetLite in our radar for some time now but haven't pulled the trigger yet on integrating it as a first class citizen in our codebase. What would be your feedback on this approach rather than rewriting a separate piece of code?

**Comment by RVinoth** [comment]
Okay. let me explain the reason for creating this SDK.  I had a requirement to access the Azure IoTHub service endpoint to send commands ( Control a device) to device from a WP 8.1 phone (A demo project). Service endpoint is used for cloud to device messaging and that is supported only in Microsoft.Azure.Devices Nuget package. Unfortunately this is supported only for PC (.net) and not supported for WP8.1 and other Universal Windows Platform (UWP) applications. I took this issue to Microsoft AzureIoTHub team and they informed the same as I mentioned above. So I was searching for alternative method to do this and found a way to access the service endpoint from AMQPNetlite directly with some preparatory work for sending cloud to device messages. So I create a wrapper for that work and formed as a SDK for easy access. This SDK only support for accessing service endpoint(Cloud to Device messaging). For accessing device endpoint we can use your Microsoft.Azure.Devices.Client package for UWP. See the below link for the demo.
http://www.e-consystems.com/blog/windowsce/?p=1615
As I discussed this with a key person on Microsoft Azure IoTHub team, he asked me to share the code here for community.

**Comment by olivierbloch** [comment]
Hi @RVinoth 
Pierre's point is that there is already a C# Service client SDK here: https://github.com/Azure/azure-iot-sdks/tree/master/csharp/service that we are maintaining and that has .Net support. Do you think you can integrate your changes to add support for UWP into his code base rather than creating a separate code base?
Thanks for your efforts!!

**Comment by RVinoth** [comment]
We have already tried to build the source code of Microsoft.Azure.Devices for UWP but the problem is even the dependency nugets such as Microsoft.Azure.amqp and few encryption related namespace used are not compatible with UWP. So, We have decided to use AMQPnetlite which is compatible with UWP. Sorry. At present I don't have bandwidth to debug and port the Microsoft.Azure.Devices to UWP.

**Pull request closed without merging**
