### PR TITLE
Certification instructions

### PR DESCRIPTION
**Pull request by v-pravek**
Certification instructions for following configurations.
- Java on Windows
- Java on Linux

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@v-pravek__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by tameraw** [comment]
@v-pravek - Please sign the CLA in order to move forward with the PR. Thanks!

**Comment by v-pravek** [comment]
I signed the CLA. Right now it is pending with HCL legal team. Will proceed as soon as it is done.

**Comment by v-pravek** [comment]
https://github.com/Azure/azure-iot-sdks/pull/92

**Pull request closed without merging**
