### PR TITLE
Spike python boost & ctypes

### PR DESCRIPTION
**Pull request by mregen**
Python 2.7.11 C wrappers for windows, developed on VS 2015.
There is one ctypes and one boost::python sample to show how to use the iothub C SDK from Python.
The native code is just using iothub and boost nuget packages compiled into a native C dll which exposes the interfaces for both the python import lib and ctypes.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mregen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mregen). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by mregen** [comment]
integrated most commenst from #315

**Comment by tameraw** [comment]
@mregen - We're under the impression that you'll be submitting a new PR in place of this one. Correct? Also, can you please submit it against the develop branch? Thanks.

**Comment by mregen** [comment]
yep, the cmd line build should be ready soon. I'll have a new PR. closed.

**Pull request closed without merging**
