### PR TITLE
Port for ESP8266

### PR DESCRIPTION
**Pull request by ritazh**
@olivierbloch @tameraw @dcristoloveanu 

This PR is part of the ESP8266 port of Azure IoT C SDK. It contains updates to the mqtt samples to fix compiler errors for non C99 mode. Please take a 👀 . Thanks!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ritazh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ritazh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by olivierbloch** [comment]
Shouldn't this one be re-submitted to our new C repo since we split the repos?
@ritazh , do you think you can resubmit to the new C repo and close this one here?
Thanks

**Comment by ritazh** [comment]
@olivierbloch Got it! I will resubmit a new PR to the new C repo.

**Comment by olivierbloch** [comment]
@ritazh 
You rock! Please close this one as soon as you are done.
Thanks

**Comment by tameraw** [comment]
@ritazh - As we have recently split our repos per language, kindly resubmit this PR against the C repo.
https://github.com/Azure/azure-iot-sdk-c

**Pull request closed without merging**
