### PR TITLE
Improvements for netmf

### PR DESCRIPTION
**Pull request by josesimoes**
A couple of improvements/changes I would like to suggest.

1) Please consider adding the commented code block on Sign method?
When I implemented the NETMF port for HTTP I spent sometime figuring the correct way to use the NETMF native crypto classes. As the comment mentions, it's only usable if the assemblies are compiled with those libs included. 
My point is that this should remain in the code for someone building this from the source AND choosing to use the native NETMF crypto libs instead of the managed SHA256 calculation (that takes up flash space and it's less performant).

2) Please consider the suggested approach in Utils (regarding the AckTypeMap and AckTypeReverseMap). In NETMF RAM is at a premium and the Hastable will be taking up precious RAM. As I propose this will only take FLASH.

I've also made a correction on IotHubConnectionString introduced by a commit from yesterday.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@josesimoes__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by josesimoes** [comment]
Hi @markrad,

Further to the explanation on the commit message, I would like to say that, for some reason, I just noticed that files that I haven't touched were added to the PR. You'll please forgive my poor GitHub skills...
I meant to touch only the following ones:
- Microsoft.Azure.Devices.Client\Common\Security\SharedAccessSignatureBuilder.cs
- \Microsoft.Azure.Devices.Client\Common\Utils.cs
- Microsoft.Azure.Devices.Client\DeliveryAcknowledgement.cs
- Microsoft.Azure.Devices.Client\IotHubConnectionString.cs

**Comment by tameraw** [comment]
@josesimoes - We just updated our repo with fixes for .NETMF (develop branch). Is this breaking for you?

**Comment by josesimoes** [comment]
Hi Tamer 😄 !

I'm aware that you've guys updated the NETMF code last week. No it's not breaking for me anymore.
As I've tried to put on the PR message, those are the motivations for the changes I'm suggesting there. 
Basically: 1) to allow people to use the NETMF native crypto classes (instead of the managed SHA256) and 2) to have a better use of RAM/FLASH that are at premium in NETMF systems.

**Comment by markrad** [comment]
Hi @josesimoes,

Thank you for your input. I am reviewing your push request. Please correct me if I am mistaken but I read your comments to suggest that the code should abolish the Dictionary (in non MF) and Hashtable (in MF) and use the code that you commented as the "hard way".

In my mind I am inclined to agree with you. I updated the code to stay reasonably within the bounds of the logic used by the MF breaking code but I will not claim to be an MF expert. I was not aware that RAM is such a constrained resource on these devices that the use of a Hashtable would have such a significant effect. I very much appreciate your input on this.

Currently I don't have time to address this. My primary goal is to set up a build/integration gate that will force the C# code to be .Net MF compatible before it is allowed to be merged into develop. I think you would agree that this is a higher priority since it will prevent these build breaks getting into the code again.

If you would like to push the code exactly as you would like to see it then my colleagues and I will be happy to review it and, if we have a consensus, integrate it into our repository.

Thank you again.

_Mark Radbourne MSFT_

**Comment by josesimoes** [comment]
Hi @markrad,

I've probably overcomplicated my explanation... My opinion is that for the NETMF code, there shouldn't be any Hastable. For the other versions I'm quite alright with any of the others. I understand your point that, in order to keep the code base more consistent, in this particular case, the Dictionary could be abolished. There is no complicated search involved that absolutely calls for a Dictionary or h
Hastable. It's probably wise that decision.

And yes, NETMF devices can be really constrained on resources. On a tiny MCU it's very common to have 128kB (yes, that is kilo) of RAM on which the CLR+HA+PAL easily eats more than half the RAM.

I totally agree with you that having a gate to check NETMF code is a great addition! Please invest all the time you can on making that happen. :smile: 

Answering your question: yes please consider my PR as it is, keeping in mind the comments that we've been exchanging of course.

**Comment by markrad** [comment]
Hi @josesimoes,

Due to the additional files that ended up in your push request, I did not merge this into our repository. However, I reviewed the changes to the relevant files and manually applied them. These changes are in code review. They should be available in the develop branch in a few days.

_Mark Radbourne MSFT_

**Comment by josesimoes** [comment]
Hi Mark,

Thanks for the update!

**Comment by markrad** [comment]
Hi @josesimoes,

I integrated my version of your changes to the .Net Micro Framework today (develop branch). We are currently working on a build gate to ensure the MF is not broken by subsequent modifications to the code base. 

Thank you for your input, it is much appreciated.

_Mark Radbourne MSFT_

**Pull request closed without merging**
