### PR TITLE
Adding new nodes

### PR DESCRIPTION
**Pull request by lcarli**
new nodes to use with node-red

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lcarli__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by lcarli** [comment]
Do I really need this CLA?

**Comment by olivierbloch** [comment]
Hey @lcarli 
You actually need to link your @microsoft.com address with your GitHub account. this will allow our bot to recognize you as a Microsoft employee.
Sorry for the late answer

**Comment by tameraw** [comment]
@lcarli - Olivier will reach out to you to discuss changes to this contribution.

**Comment by tameraw** [comment]
@lcarli - As we have recently split our repos per language, kindly resubmit this PR against the node repo if still of interest. 
https://github.com/Azure/azure-iot-sdk-node

**Pull request closed without merging**
