### PR TITLE
Fix a bug amqp uri using Client.fromSharedAccessSignature

### PR DESCRIPTION
**Pull request by kajiiiro**
I fix a bug in Client.fromSharedAccessSignature(iothub device sdk).
and typo console.error.
#308 #312

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kajiiiro__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@kajiiiro__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by pierreca** [comment]
Looks good to me :) I'll pull it in as soon as you sign the CLA, instructions were provided by the automatic comment by @azurecla

**Comment by kajiiiro** [comment]
I ask my boss to sign CLA.
Please wait until Monday in Japan.

**Comment by azurecla** [comment]
__@kajiiiro__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by pierreca** [comment]
Thanks @kajiiiro, this has been merged into the develop and will make it to the packages with the next release!

**Pull request merged**
