### PR TITLE
Python checking if parameter is callable rather than function

### PR DESCRIPTION
**Pull request by damienpontifex**
Allowing for more types to be passed as callback parameters by utilising a callable check including class methods

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@damienpontifex__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by mregen** [comment]
@damienpontifex, looks good. Could you also provide a Python sample showing what's improved after this change?

**Comment by damienpontifex** [comment]
Will add a sample and include with this.

**Comment by damienpontifex** [comment]
@mregen see second commit with sample that defines class methods as callbacks. Tested PyCallable_Check code with this sample and original amqp sample and all works fine.

**Comment by mregen** [comment]
@damienpontifex, I like your amqp sample better than the existing one. If you don't mind I'd use it to replace the original amqp sample. Thanks a lot for the contribution, I'll kick off the jenkins process asap!

**Comment by damienpontifex** [comment]
@mregen do you want me to rename/replace the previous amqp sample and integrate with this PR? Or you're going to cleanup after jenkins feedback?

**Comment by mregen** [comment]
@damienpontifex, no worries, for now they can sit side by side and before next release I'll clean up and may just delete the old sample.. there have also been some updates to the c samples in the meantime which i need to integrate anyway, like cert support. I wonder if it were useful to have a simple 'get' function instead of get_string/get_bytearray and a get_content_type. Thoughts?

**Comment by mregen** [comment]
@damienpontifex, could you do me a favor and squash the commits? I hit a problem merging your change, because  	b0a70f4 contains an empty file

**Comment by damienpontifex** [comment]
Will do. I don't even know what that empty file is. Will try and remove it from the commit also

**Comment by damienpontifex** [comment]
@mregen squashed and removed that empty file

**Pull request merged**
