### PR TITLE
cpp wrapper around the c iothub_client

### PR DESCRIPTION
**Pull request by damienpontifex**
Work on a C++ thin wrapper around the C API. Work associated with #751 

@tameraw would be interested in review for changes/additions. I haven't added tests at this stage as I have been focusing on it being a wrapper for convenience rather than adding additional functionality at this stage as discussed in the original issue.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@damienpontifex__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by tameraw** [comment]
@damienpontifex - Thanks a lot for providing this CPP wrapper. We'll review it and provide you with comments if anything needs to be addressed.

**Comment by tameraw** [comment]
@damienpontifex - Can you please create a new repo  for C++ and introduce the C++ wrapper there? You can use our SDK as a submodule into that new repo and we would be happy to provide you feedback directly in your repo. We can also provide a link in our readme to point to your solution.
Thanks.

**Comment by damienpontifex** [comment]
Hi @tameraw my vision would be that this would also be used by the python client that has cpp classes utilising boost to add functionality.

There is basically a cpp wrapper there, but unusable to straight cpp. Subclasses of these could be made for the python client and hence produce a more easily maintainable python version, plus a cpp wrapper.

Thoughts/additions?

**Comment by tameraw** [comment]
@damienpontifex - We would definitely consider utilizing your cpp wrapper  for python as well, if that works with no issues (good idea for sure). 
Having said that, at this point, we prefer to have the cpp wrapper in a separate repo. Thanks.

**Comment by damienpontifex** [comment]
No worries @tameraw. Thank you for considering this pull request.

**Pull request closed without merging**
