### PR TITLE
add submodule https://github.com/Azure/device-discovery-cli.git

### PR DESCRIPTION
**Pull request by ZhijunZhao**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ZhijunZhao__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (zhijzhao). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ZhijunZhao** [comment]
@tameraw readme.md file has been added to the repo. Please help to review this pull request.

Also, add @reyang @aovechki for awareness.

**Comment by ZhijunZhao** [comment]
@tameraw Could you help to take a look at this pull request?

**Comment by tameraw** [comment]
This branch has been merged.

**Pull request closed without merging**
