### PR TITLE
Io t hub node gateway

### PR DESCRIPTION
**Pull request by lcarli**
IoTHubNode prepared for Gateways

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lcarli__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by pierreca** [comment]
Hi @lcarli 

we already have a node-red module here: 
https://github.com/Azure/azure-iot-sdks/tree/master/node/device/node-red

Have you considered using it?

Also I see your module is regrouping some features of the device and the service SDK. i'd love to hear the scenarios you have in mind that require this.

**Comment by lcarli** [comment]
Hi, Pierre. My node is a fork of this original one. But I did some improves requested by our clients like:receive messages from more than one device. You can pass DeviceId and Key thru the payload, instead use as credentials. AT&T are using those nodes around the world and Intel Gateway in some countries.

**Comment by olivierbloch** [comment]
Hi @lcarli 
I think your changes would work well as an option to the existing node. if there are credentials in the payload, then the node sends using these credentials, and if there are no credentials in the payload then the node sends using the ones from the configuration...
How do you deal with receiving messages from IoT Hub?

I don't want to duplicate the number of node-RED nodes, so if you could refactor the pull request and contribute your changes into node/device/node-red/azureiothub that'd be great.
Thanks

**Comment by olivierbloch** [comment]
Hi @lcarli 
any update on this one?
Thanks

**Comment by olivierbloch** [comment]
Closing as conversation is stale. Please feel free to reopen if you want to move forward. Thanks

**Pull request closed without merging**
