### PR TITLE
Certification instructions

### PR DESCRIPTION
**Pull request by v-pravek**
Adding certification instructions for following environments
- Java on Linux
- Java on Windows

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@v-pravek__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by andrew-buckley** [comment]
Hi @v-pravek, it seems as though you are using an old version of the SDK and consequently an outdated version of the Device Explorer. I've already updated the instructions and screenshots on the other certification documents, but please update this one using the most recent version of the Device Explorer.

Thanks!

**Comment by v-pravek** [comment]
Hi Andrew, I used iot_certification_linux_java document with latest SDK from https://github.com/Azure/azure-iot-sdks and downloaded device explorer MSI from https://github.com/Azure/azure-iot-sdks/blob/master/tools/DeviceExplorer/doc/how_to_use_device_explorer.md.
I followed doc as per current steps and was able to validate it E2E on Ubuntu.

I Noticed that behavior was same as document's existing screenshots. Can you please point me which screenshots and instructions are outdated. It will help me to identify the gap.

**Comment by andrew-buckley** [comment]
It seems as though some of your screenshots of the Device Explorer are of the more recent version and some are of the older version. The newest version of the Device Explorer replaces the "Notification" tab with "Message To Device", and within that ab replaces the "Notification" text field with the "Message" text field. Here is a list of which screenshots are outdated: 3_3_1_01.png (the one in the images folder for both the Linux and Windows instructions), device_explorer_amqp_message_received.PNG (Linux), device_explorer_http_message_received.PNG (Linux), device_explorer_message_send.PNG (both Linux and windows). The certification instructions also reference the "Notification" tab and "Notification" field which no longer exists as noted above. They should now read, respectively, "Message to Device" and "Message".

Additionally, the console window screenshots for the Linux Java instructions seem to be using an older preview version.

**Comment by v-pravek** [comment]
Thanks a lot Andrew. Will send new pull request with updated details..

**Pull request closed without merging**
