### PR TITLE
added new getting started document

### PR DESCRIPTION
**Pull request by iantracy1**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@iantracy1__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by iantracy1** [comment]
I completed the cla.

**Comment by azurecla** [comment]
__@iantracy1__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by tameraw** [comment]
@iantracy1 - Thanks for submitting this pull request. As we now have a separate repo for these documents, can you please resubmit this PR against that new repo?
https://github.com/Azure/azure-iot-device-ecosystem

Thanks.

**Comment by iantracy1** [comment]
@tameraw Yes, Will do. I was not aware of the other Repo. Thanks!

**Comment by ashokkhurana** [comment]
Closing this PR because this document is already chcked-in by iotcert team in new repo https://github.com/Azure/azure-iot-device-ecosystem/blob/master/get_started/linux-netbiter-ec350-oem-c.md .

**Pull request closed without merging**
