### PR TITLE
Fork some javax.* classes to make using HTTPS on Android easier

### PR DESCRIPTION
**Pull request by gustafsonk**
In addition to the DatatypeConverter class I mentioned in #25, I also found the SizeLimitExceededException class that is not part of the Android library. I basically copy-pasted the source code of the methods that were needed out of their original files in the Java 7.0.79 SDK. With these changes I'm able to only reference the .jar file generated by Maven and use HTTPS successfully in an Android app.

### CODE REVIEW

**Comment by damonbarry** [comment]
We don't want to redistribute Java source code from this repository.

A colleague tells me the conventional approach is to use Android's Base64 class.  Can we come up with an approach that uses Base64 and doesn't copy Java source code?

**Comment by tameraw** [comment]
Hello,
Just following up if there is any update on this PR. (Can you please take a look at Damon's suggestion?)
Thanks,
-Tamer

**Comment by gustafsonk** [comment]
My goal was to make this SDK work using HTTPS for both java and android with the minimal required changes. I don't think I will have time to update this anytime soon, but feel free to ditch it or modify it as you see fit.

**Comment by tameraw** [comment]
@gustafsonk - Thanks for your feedback.
We are tracking making this change in our backlog as part of enabling Android and we're closing this PR.

**Comment by btusca** [comment]
Hi Tameraw! Any news about the implementation of azure-iot-sdk in Android? How can we do to get it working in Android?

**Pull request closed without merging**
