### PR TITLE
Capture properties in node client over HTTP when receiving messages

### PR DESCRIPTION
**Pull request by stuartleeks**
Helps to address #414 when receiving messages

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stuartleeks__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stuartle). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by pierreca** [comment]
Hi @stuartleeks, thanks for submitting the PR.
would you mind resubmitting it against the `develop` branch? per our contribution guidelines, this is where code should go before it's released so that we can run our gated build on it. 

Also, it'd be great if there were unit tests associated with this addition. we're trying to keep the code coverage as high as possible :) 

Thanks!

**Comment by stuartleeks** [comment]
Hi @pierreca,

I'd be happy to look at adding some tests :-)

Are there any docs on getting the node builds and tests running? It wasn't obvious to me how to use the build scripts.

Stuart

**Comment by pierreca** [comment]
@stuartleeks That's a great question :) Here's a doc I stated writing to answer it - please let me know if that helps and if you'd like to see other things detailed in here. 

https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/node-tests.md

**Comment by tameraw** [comment]
@stuartleeks - Any chance you're able to get to the testing for this PR?

**Comment by stuartleeks** [comment]
I started to look at it, but ran into issues getting everything set up on my machine to run the tests :-(

**Comment by pierreca** [comment]
@stuartleeks what problems did you run into?

**Comment by stuartleeks** [comment]
From memory, after running through the dev-setup I still hit errors with `describe` not being recognised

**Comment by stuartleeks** [comment]
I just grabbed the code again and rebased on develop. Looks like a similar change has been implemented already. There's a slight difference between my submission and what is implemented.

In the .NET SDK, if you add a property ("myproperty") this is added as a HTTP header iothub-app-myproperty.

In the implementation, this is added to the message properties with "iothub-app-myproperty" as the property name whereas in my submission (and I believe the .NET SDK) this would be surfaced with property "myproperty"

**Comment by pierreca** [comment]
that right, we did fix this a couple weeks ago... in HTTP and AMQP. well I guess we can close the PR then. feel free to reopen it if something doesn't work the way you'd expect.

**Pull request closed without merging**
