### PR TITLE
Fix msg properties lost via http netmf

### PR DESCRIPTION
**Pull request by josesimoes**
this fixes issue #142 in NETMF client

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@josesimoes__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by josesimoes** [comment]
@networkfusion I'm afraid that the AMQP is on hold... right now I'm terribly busy with company projects taking all my time.
I did the HTTP part, maybe someone else from the community wants to volunteer to work on the AMQP... :wink:

**Comment by networkfusion** [comment]
@josesimoes I am willing to give it a go but would need some guidance from you with regard to your plan for the tiny version of AMQPNetLite and which bits you were struggling with. I am also busy with work stuff but some of it involves this so I can spend some time on it especially, if I can make the implementation recover from failures better than my attempt at the moment. Perhaps someone from the core team is willing to help also?!

**Comment by josesimoes** [comment]
@networkfusion AMQPNetLite is pretty much completed (note that I'm not part of the core team here or at AMQPNetLite, just contributed to the development). As fas as I know it has everything required to be usable with the Azure IoT SDK. (except for the CBS auth...)

I would suggest that you follow the HTTP implementation. Then start adding the "missing" files for AMQP and fill in the missing bits in the core files that already there for the HTTP part. All the core ones are already there. 
Mind the method naming. I remove the async from the internal names and left some methods blank just to keep the call stack "in sync" with the full NET SDK. Be aware that it may look daunting at a first glance! :smile: The code base has a LOT of layers!

If you get stuck with something ping me. As I've already gone through all that code I'll probably remember it and can help you.

**Pull request merged**
