### PR TITLE
AmqpWs support for node.js service client

### PR DESCRIPTION
**Pull request by wmmihaa**
Added support for AmqpWs to the node.js service client after suggestion from @pierreca. 

**Added**: node/service/lib/amqp-ws.js
_amqp-ws transport class that inherits from the amqp class_

**Updated**: node/service/iothub.js
_Added exports for Amqp and AmqpWs_

**Updated**: node/service/lib/client.js
_Updated the fromConnectionString and fromSharedAccessSignature operations as:_

- Changed the 'value' parameter name to connStr and sharedAccessSignature
- Added Transport parameter
- Added setting Transport to DefaultTransport if not set
- Updated comments

**Left to do**
_No unit tests has been added or updated_

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@wmmihaa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by pierreca** [comment]
Hi @wmmihaa, 

you're carrying a bunch of changes from master to develop in addition to your changes. basically the PR should only be a diff between our `develop` branch and a branch you forked from it. 

if you feel like reforking and doing the pull request, go for it but I feel bad for making you jump through that many hoops... so if you don't feel like it I'llwork with one of the existing PRs that you submitted (cherrypicking or something like that). your call. Sorry, I'll try to make our contribution guidelines clearer...

**Comment by wmmihaa** [comment]
No worries, it's my fault. I'' fix it right away.

Date: Thu, 14 Apr 2016 23:34:49 -0700

**Comment by wmmihaa** [comment]
Stupid question... Now that I already have a fork of the master branch, how can I create a new one from the dev branch?  

Date: Thu, 14 Apr 2016 23:34:49 -0700

**Comment by wmmihaa** [comment]
Sorry to have caused you any headaches making PR's from (and to) the wrong branch. #488 should be right and you can disregard this and #485.

**Pull request closed without merging**
